# Generated by Django 3.2.6 on 2021-08-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20210807_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(limit_choices_to={'is:public': True}, on_delete=django.db.models.deletion.CASCADE, to='instagram.post'),
        ),
    ]
